-- apply changes
create table account (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  first_name                    varchar(128) not null,
  last_name                     varchar(128) not null,
  email                         varchar(512) not null,
  address                       varchar(512) not null,
  city                          varchar(256) not null,
  zip_code                      varchar(16) not null,
  additional_address            varchar(256),
  coordinate                    geometry(point,4326) not null,
  phone_number                  varchar(16) not null,
  profile_picture               varchar(1024),
  password                      varchar(256),
  google_id                     varchar(32),
  facebook_id                   varchar(32),
  twitter_id                    varchar(32),
  last_login                    timestamptz,
  active                        boolean not null,
  email_verified                boolean not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_account_uid unique (uid),
  constraint uq_account_email unique (email),
  constraint uq_account_google_id unique (google_id),
  constraint uq_account_facebook_id unique (facebook_id),
  constraint uq_account_twitter_id unique (twitter_id),
  constraint pk_account primary key (id)
);

create table booked_care (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  booked_care_type              varchar(9) not null,
  start_date                    timestamptz not null,
  end_date                      timestamptz,
  duration                      bigint not null,
  parent_id                     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint ck_booked_care_booked_care_type check ( booked_care_type in ('ONE_TIME','RECURRENT')),
  constraint uq_booked_care_uid unique (uid),
  constraint pk_booked_care primary key (id)
);

create table booked_care_children (
  booked_care_id                bigint not null,
  children_id                   bigint not null,
  constraint pk_booked_care_children primary key (booked_care_id,children_id)
);

create table caf_option (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  opt_key                       varchar(32) not null,
  opt_value                     TEXT,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_caf_option_uid unique (uid),
  constraint uq_caf_option_opt_key unique (opt_key),
  constraint pk_caf_option primary key (id)
);

create table care_criteria (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  gender                        boolean default false not null,
  have_car                      boolean default false not null,
  speaks_english                boolean default false not null,
  experience_with_children      boolean default false not null,
  smoke                         boolean default false not null,
  childhood_training            boolean default false not null,
  booked_care_id                bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_care_criteria_uid unique (uid),
  constraint uq_care_criteria_booked_care_id unique (booked_care_id),
  constraint pk_care_criteria primary key (id)
);

create table children (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  first_name                    varchar(64),
  category                      varchar(24) not null,
  birth_date                    date,
  parent_id                     bigint not null,
  usual_childcare               varchar(24),
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint ck_children_category check ( category in ('UNDER_3_YEARS','UNDER_6_YEARS','OVER_6_YEARS','BIRTHDAY')),
  constraint ck_children_usual_childcare check ( usual_childcare in ('KINDERGARTEN','PUBLIC_NURSERY','MATERNAL_ASSISTANCE','PRIVATE_NURSERY','OTHER')),
  constraint uq_children_uid unique (uid),
  constraint pk_children primary key (id)
);

create table children_has_booked_care (
  children_id                   bigint not null,
  booked_care_id                bigint not null,
  constraint pk_children_has_booked_care primary key (children_id,booked_care_id)
);

create table effective_care (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  status                        varchar(12) not null,
  start_date                    timestamptz not null,
  end_date                      timestamptz,
  booked_care_id                bigint not null,
  effective_unavailability_id   bigint,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint ck_effective_care_status check ( status in ('PLANNED','ASSIGNED','PERFORMED','CANCELLED','UNSUCCESSFUL')),
  constraint uq_effective_care_uid unique (uid),
  constraint uq_effective_care_effective_unavailability_id unique (effective_unavailability_id),
  constraint pk_effective_care primary key (id)
);

create table effective_unavailability (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  start_date                    timestamptz not null,
  end_date                      timestamptz,
  planned_unavailability_id     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_effective_unavailability_uid unique (uid),
  constraint pk_effective_unavailability primary key (id)
);

create table parent_criteria (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  gender                        boolean default false not null,
  have_car                      boolean default false not null,
  speaks_english                boolean default false not null,
  experience_with_children      boolean default false not null,
  smoke                         boolean default false not null,
  childhood_training            boolean default false not null,
  parent_id                     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_parent_criteria_uid unique (uid),
  constraint uq_parent_criteria_parent_id unique (parent_id),
  constraint pk_parent_criteria primary key (id)
);

create table parent (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  account_id                    bigint not null,
  sponsor_code                  varchar(16) not null,
  sponsor_id                    bigint,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_parent_uid unique (uid),
  constraint uq_parent_account_id unique (account_id),
  constraint uq_parent_sponsor_code unique (sponsor_code),
  constraint pk_parent primary key (id)
);

create table parent_option (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  opt_key                       varchar(32) not null,
  opt_value                     TEXT,
  parent_id                     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_parent_option_uid unique (uid),
  constraint uq_parent_option_parent_id_opt_key unique (parent_id,opt_key),
  constraint pk_parent_option primary key (id)
);

create table planned_unavailability (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  sitter_unavailability_type    varchar(9) not null,
  start_date                    timestamptz not null,
  end_date                      timestamptz,
  duration                      bigint not null,
  sitter_id                     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint ck_planned_unavailability_sitter_unavailability_type check ( sitter_unavailability_type in ('ONE_TIME','RECURRENT')),
  constraint uq_planned_unavailability_uid unique (uid),
  constraint pk_planned_unavailability primary key (id)
);

create table role (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  role                          varchar(32) not null,
  account_id                    bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint ck_role_role check ( role in ('NONE','ROLE_PARENT','ROLE_SITTER','ROLE_ADMIN')),
  constraint uq_role_uid unique (uid),
  constraint pk_role primary key (id)
);

create table sitter_attribute (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  gender                        boolean default false not null,
  have_car                      boolean default false not null,
  speaks_english                boolean default false not null,
  experience_with_children      boolean default false not null,
  smoke                         boolean default false not null,
  childhood_training            boolean default false not null,
  guard_type                    varchar[] not null,
  experiences                   varchar[] not null,
  experience_types              varchar[] not null,
  situation                     varchar(32) not null,
  situation_detail              TEXT,
  certifications                varchar[] not null,
  extra_certification           TEXT,
  spoken_languages              varchar[] not null,
  homework_capabilities         varchar[] not null,
  car_situation                 varchar(24) not null,
  public_transports             varchar[] not null,
  availabilities                varchar[] not null,
  commendation                  TEXT,
  information                   TEXT,
  sitter_id                     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint ck_sitter_attribute_situation check ( situation in ('STUDENT','ACTIVE_WITH_CHILDREN','ACTIVE_WITHOUT_CHILDREN','SENIOR')),
  constraint ck_sitter_attribute_car_situation check ( car_situation in ('YES','NO_BUT_PLANNED','NO')),
  constraint uq_sitter_attribute_uid unique (uid),
  constraint uq_sitter_attribute_sitter_id unique (sitter_id),
  constraint pk_sitter_attribute primary key (id)
);

create table sitter (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  account_id                    bigint not null,
  birthday                      date,
  picture                       BYTEA,
  picture_mime_type             varchar(32),
  picture_etag                  varchar(32),
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_sitter_uid unique (uid),
  constraint uq_sitter_account_id unique (account_id),
  constraint pk_sitter primary key (id)
);

create table sitter_option (
  id                            bigint generated by default as identity not null,
  uid                           uuid not null,
  created_at                    timestamptz not null,
  last_update                   timestamptz not null,
  opt_key                       varchar(32) not null,
  opt_value                     TEXT,
  sitter_id                     bigint not null,
  deleted                       BOOLEAN DEFAULT FALSE not null,
  constraint uq_sitter_option_uid unique (uid),
  constraint uq_sitter_option_sitter_id_opt_key unique (sitter_id,opt_key),
  constraint pk_sitter_option primary key (id)
);

create index ix_booked_care_parent_id on booked_care (parent_id);
alter table booked_care add constraint fk_booked_care_parent_id foreign key (parent_id) references parent (id) on delete restrict on update restrict;

create index ix_booked_care_children_booked_care on booked_care_children (booked_care_id);
alter table booked_care_children add constraint fk_booked_care_children_booked_care foreign key (booked_care_id) references booked_care (id) on delete restrict on update restrict;

create index ix_booked_care_children_children on booked_care_children (children_id);
alter table booked_care_children add constraint fk_booked_care_children_children foreign key (children_id) references children (id) on delete restrict on update restrict;

alter table care_criteria add constraint fk_care_criteria_booked_care_id foreign key (booked_care_id) references booked_care (id) on delete restrict on update restrict;

create index ix_children_parent_id on children (parent_id);
alter table children add constraint fk_children_parent_id foreign key (parent_id) references parent (id) on delete restrict on update restrict;

create index ix_children_has_booked_care_children on children_has_booked_care (children_id);
alter table children_has_booked_care add constraint fk_children_has_booked_care_children foreign key (children_id) references children (id) on delete restrict on update restrict;

create index ix_children_has_booked_care_booked_care on children_has_booked_care (booked_care_id);
alter table children_has_booked_care add constraint fk_children_has_booked_care_booked_care foreign key (booked_care_id) references booked_care (id) on delete restrict on update restrict;

create index ix_effective_care_booked_care_id on effective_care (booked_care_id);
alter table effective_care add constraint fk_effective_care_booked_care_id foreign key (booked_care_id) references booked_care (id) on delete restrict on update restrict;

alter table effective_care add constraint fk_effective_care_effective_unavailability_id foreign key (effective_unavailability_id) references effective_unavailability (id) on delete restrict on update restrict;

create index ix_effective_unavailability_planned_unavailability_id on effective_unavailability (planned_unavailability_id);
alter table effective_unavailability add constraint fk_effective_unavailability_planned_unavailability_id foreign key (planned_unavailability_id) references planned_unavailability (id) on delete restrict on update restrict;

alter table parent_criteria add constraint fk_parent_criteria_parent_id foreign key (parent_id) references parent (id) on delete restrict on update restrict;

alter table parent add constraint fk_parent_account_id foreign key (account_id) references account (id) on delete restrict on update restrict;

create index ix_parent_sponsor_id on parent (sponsor_id);
alter table parent add constraint fk_parent_sponsor_id foreign key (sponsor_id) references parent (id) on delete restrict on update restrict;

create index ix_parent_option_parent_id on parent_option (parent_id);
alter table parent_option add constraint fk_parent_option_parent_id foreign key (parent_id) references parent (id) on delete restrict on update restrict;

create index ix_planned_unavailability_sitter_id on planned_unavailability (sitter_id);
alter table planned_unavailability add constraint fk_planned_unavailability_sitter_id foreign key (sitter_id) references sitter (id) on delete restrict on update restrict;

create index ix_role_account_id on role (account_id);
alter table role add constraint fk_role_account_id foreign key (account_id) references account (id) on delete restrict on update restrict;

alter table sitter_attribute add constraint fk_sitter_attribute_sitter_id foreign key (sitter_id) references sitter (id) on delete restrict on update restrict;

alter table sitter add constraint fk_sitter_account_id foreign key (account_id) references account (id) on delete restrict on update restrict;

create index ix_sitter_option_sitter_id on sitter_option (sitter_id);
alter table sitter_option add constraint fk_sitter_option_sitter_id foreign key (sitter_id) references sitter (id) on delete restrict on update restrict;

